baseURL = "https://golazy.dev/"
locale = "en-US"
title = "golazy.dev"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]

[params]
description = "GoLazy is a convention-first web framework for building clear, fast Go applications."
repository = "https://github.com/golazy/golazy"
tagline = "TOgether WE BUild."
guidesVersion = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
